containers/podlet

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/cli/container.rs
- src/cli/container/podman.rs
- src/cli/container/quadlet.rs
- src/cli/install.rs
- src/cli/kube.rs
- src/cli/network.rs
- src/cli/service.rs
- src/cli/unit.rs
- src/cli/volume.rs
- src/cli/volume/opt.rs
- src/main.rs
Adds options to the base `podlet` command for adding common options to the [Unit] and [Install] sections and for writing to a file instead of stdout.
> Unit, install, and file options

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
Closes #12, adds an option flag for putting the generated file in the appropriate directory for quadlet. Also prepares for a v0.1.1 release.
> Unit directory option flag

- README.md
> Podman how to (#1)

- .github/workflows/release-container.yml
- Containerfile
- src/cli/container/quadlet.rs
Hopefully fixes CI container releases. Upgrades podman to the latest version as the buildah/podman version in Ubuntu 22.04 has a bug where the TARGETPLATFORM arg is not set correctly. Also changed to using roughly the same commands I used to build and upload the last two versions of the container.
Switched to using cargo-binstall to install cargo-chef in the container and only install `gcc-aarch64-linux-gnu` on arm64 builds.
> Fix release container ci

- src/cli/container/podman.rs
- src/cli/container/quadlet.rs
- src/quadlet/container.rs
Gonna be honest, don't entirely understand the codebase (or rust for that matter) but I tried to match this up with the existing params best I could (cap_add seemed to be the most similar so I based on that mostly) and it appears to work fine in accordance with the [quadlet man page](https://man.archlinux.org/man/quadlet.5.en)
> Add support for --sysctl

- .github/workflows/ci.yaml
- README.md
- src/cli/container/podman.rs
- src/cli/container/quadlet.rs
- src/cli/kube.rs
- src/cli/network.rs
- src/quadlet.rs
- src/quadlet/container.rs
- src/quadlet/kube.rs
- src/quadlet/network.rs
Closes #29.
Adds support for quadlet options introduced in podman v4.7.0, bumping the minimum supported podman version.
> Podman v4.7.0

- src/cli/container/quadlet.rs
Closes #38
- Support all `podman run --network` values for service `network_mode`
- Improve error message for unsupported values, link to the podman docs
The error message for `network_mode` values of `service` now looks like:
```
Error: 
0: Could not parse service `test` as a valid podman command
1: network_mode `service:` is not supported by podman
Location:
src/cli/container/quadlet.rs:807
Suggestion: try using the `container:` network_mode instead
Suggestion: see the --network section of the podman-run(1) documentation for supported values: https://docs.podman.io/en/stable/markdown/podman-run.1.html#network-mode-net
```
> fix(compose): `network_mode` accept all podman values

- src/cli.rs
- src/cli/generate.rs
- src/cli/network.rs
- src/cli/volume.rs
- src/cli/volume/opt.rs
- src/quadlet.rs
- src/quadlet/network.rs
Closes #23
Adds the `podlet generate` command for generating container, network, or volume quadlets from an existing resource. Similar to the `podman generate` commands.
> Generate quadlet from an existing container, network, or volume

- README.md
I am curious why you would suggest that. I have just spend useless time debugging why my path could not be found, because I blindly copied that command and thought it was just a 1:1 mapping.
If podlet does not support user systemd directories, it should also not support that in the container due to some strange mapping, should it? If it does support that, then no reason to re-map it, it should work as usual, should not it?
> Readme container doc: map user into podlet container

- src/cli/unit.rs
- src/quadlet/container/mount/idmap.rs
Brings `Unit` inline with the other sections of the generated quadlet file.
Fixes: #64
> fix: use quadlet serializer for `Unit` `Display` impl

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/cli/compose.rs
- src/cli/container.rs
- src/cli/container/compose.rs
- src/cli/container/podman.rs
- src/cli/container/quadlet.rs
- src/cli/global_args.rs
- src/cli/k8s.rs
- src/cli/k8s/service.rs
- src/cli/k8s/service/mount.rs
- src/cli/k8s/volume.rs
- src/cli/network.rs
- src/cli/service.rs
- src/cli/unit.rs
- src/cli/volume.rs
- src/quadlet/container.rs
- src/quadlet/container/device.rs
- src/quadlet/container/mount.rs
- src/quadlet/container/volume.rs
- src/quadlet/kube.rs
- src/quadlet/network.rs
- src/quadlet/volume.rs
Changes the library used for deserializing a compose file from `docker-compose-types` to [`compose_spec`](https://github.com/k9withabone/compose_spec_rs). Most of the conversion logic was refactored/rewritten and hopefully readability and maintainability have improved in those areas. `compose_spec` is a lot stricter about what it accepts as a valid compose file. This is a **breaking change** as some compose files (those that don't comply with the spec) will no longer successfully deserialize and convert.
A new `--binds-to` option was added, which sets [`BindsTo=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#BindsTo=) in the `[Unit]` section. It was needed for converting from [long syntax `depends_on`](https://github.com/compose-spec/compose-spec/blob/master/05 …
> Migrate to `compose_spec`

- CHANGELOG.md
The release of Podlet v0.3.0 was delayed by a few days, this updates the release date to today.
> docs(changelog): fix v0.3.0 release date

- README.md
Since the package was added to homebrew (https://formulae.brew.sh/formula/podlet), maybe you'd like to add it to the installation section of the readme.
> docs: add homebrew to the installation section

- .github/workflows/release-container.yml
The `--all` option is not true by default for `buildah manifest push` like it is for `podman manifest push`. `--all` makes Buildah push the images in addition to the manifest.
Fixes: #82
> ci(release-container): add `--all` to `buildah manifest push`

- src/cli/pod.rs
> fix: Read pod name from podman create args

- src/cli/container/quadlet.rs
Fixed bug introduced in commit d3da789 where `.network` was not appended to network names for the container `Network=` Quadlet option when converting from a Compose file.
Fixes #90
> fix(compose): append `.network` to container network name

- src/cli/generate.rs
Podman v5.0.0 and newer always returns an array from `podman inspect`. Older versions of Podman may return a single JSON object if there is only one result, notably for `podman pod inspect`.
Created a `serde::de::Visitor` for deserializing the output of `podman inspect` which accepts a map (object) or sequence (array).
Tested with both Podman v5.2.2 and v4.9.4 (via quay.io/containers/podman:v4.9.4 image).
Fixes: #94
> fix(generate): accept array or object from `podman inspect` output

- src/cli/compose.rs
- src/cli/unit.rs
When the `podlet compose --pod` option is used, the names of the services from the Compose file are prepended with the pod name. If a service had a dependency via the `depends_on` attribute, the name of the dependency was not similarly prepended with the pod name when added to the `[Unit]` section of the Quadlet file.
Changed `podlet::cli::compose::service_try_into_quadlet_file()` to handle all service name changes when the `--pod` option is used.
Fixes: #114
> fix(compose): prepend container dependencies with pod name

- src/cli/generate.rs
Added `--ignore-infra-conmon-pidfile` and `--ignore-pod-id-file` options to `podlet generate pod`.
The `--infra-conmon-pidfile` and `--pod-id-file` options are deliberately unimplemented by `podlet podman pod create` as they are set by Quadlet when generating the systemd service unit file, and cannot be set multiple times. Because `podlet generate pod` uses `podlet podman pod create` internally, this caused an error when attempting to generate a `.pod` Quadlet file from a pod created using either of those options, such as those created with the deprecated `podman generate systemd` command.
Closes: #86
> feat(generate): add options to ignore unsupported pod options

- src/cli.rs
- src/cli/container/quadlet.rs
- src/cli/generate.rs
Changed short help flag to `-?` for `podlet podman run`. This could be a potentially minor breaking change for some users.
Fixes: #105
> fix(container): support short flag `-h` for `podman run --hostname`
